development: 
  adapter: mysql2 
  database: contact_form_dev
  username: root 
  password: password
test: 
  adapter: mysql2 
  database: contact_form_test
  username: root
  password: password
production: 
  adapter: mysql2
  database: contact_form_prod
  username: root
  password: password